### ISSUE TITLE
Fix the PORT number in the docker compose docs

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#10]
### Description

Fix the port number to `9001`

### Screenshots

<img width="810" alt="Screenshot 2023-02-10 at 12 48 35 PM" src="https://user-images.githubusercontent.com/51878265/218027540-32c5e00d-947b-4ed7-95fd-f773f30bd946.png">

**Comment by kalyan-vurugonda** [comment]
Hi @Pradumnasaraf, I would like to contribute to this issue

**Comment by Pradumnasaraf** [comment]
Go ahead

**Comment by Pradumnasaraf** [comment]
Fixed in #12
