### ISSUE TITLE
[DOCS] Add a missing instruction in README

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#11]
### Description

Add a line below Step 2 in **Local Setup** by saying that.

Line needs to be added - **"You can access the API at localhost:9001"**

### Screenshots

<img width="810" alt="Screenshot 2023-02-10 at 12 50 49 PM" src="https://user-images.githubusercontent.com/51878265/218028283-cd8307a2-47ea-43c2-80b5-889a961116d2.png">

**Comment by kelvinparmar** [comment]
@Pradumnasaraf 
I would like to contribute in this issue

**Comment by kalyan-vurugonda** [comment]
Hi @Pradumnasaraf, I would like to contribute to this issue

**Comment by AryanGupta99** [comment]
hey @Pradumnasaraf  let me do it

**Comment by Pradumnasaraf** [comment]
Hey, @kalyan-vurugonda I already assigned you one issue. @AryanGupta99 there are more open ones please look at them.

Go ahead with this @kelvinparmar

**Comment by kalyan-vurugonda** [comment]
Ok, Pradumna!
