### ISSUE TITLE
[DOCS] Add CONTRIBUTING.md 

### ISSUE THREAD

**Issue by theselaw** [Pradumnasaraf/Post-My-Message#18]
### Description

I think a Contributing.md File can be added to better to guide contributors on the right way to contribute.

**Comment by Pradumnasaraf** [comment]
Yes, we need that I was about to raise an issue about that. Thank you for opening the issue. 

It should be like https://github.com/Pradumnasaraf/open-source-with-pradumna/blob/main/CONTRIBUTING.md . Just modifying the links.

**Comment by Pradumnasaraf** [comment]
Would you like to work on this @theselaw?

**Comment by chottuthejimmy** [comment]
I would like to work on this , can you assign this to me

**Comment by theselaw** [comment]
Yeah, Sure.

I can get on it right away.
