### ISSUE TITLE
[FEATURE] Adding Light and Dark mode

### ISSUE THREAD

**Issue by mithindev** [Pradumnasaraf/Post-My-Message#21]
## Problem

Currently, the website only supports a single visual style. This can be challenging for users who prefer to view websites in a darker or lighter mode, depending on the time of day or other personal preferences.

## Proposed Solution

I propose adding a feature that allows users to switch between dark and light modes for the website. This would allow users to view the website in a visual style that is comfortable for them, regardless of the time of day or lighting conditions.

## Implementation Details

- Add a toggle button to switch between dark and light modes.
- Define the styles for each mode in CSS.
- Store the user's preference for mode (dark or light) in local storage, so that the user's preferred mode is remembered across multiple visits to the website.
- Update the JavaScript code to apply the appropriate styles based on the user's preference.

## Benefits

- Improved accessibility and usability for users who prefer to view websites in a darker or lighter mode.
- Better user experience, as users will be able to view the website in a style that is comfortable for them.

**Comment by mithindev** [comment]
"I would like to express my interest in working on this issue. Could you kindly assign it to me so that I can contribute my efforts to resolve it?

**Comment by Pradumnasaraf** [comment]
Hey. 
It is an API project, so we have just a basic landing page with simple text to tell API is live it has nothing to do with the usability or anything else. So I don't think these changes are necessary at the moment.

Thank you for your effort and for opening the issue.

**Comment by mithindev** [comment]
Thank you.
