### ISSUE TITLE
[FEATURE] Add a name to greetings workflow

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#27]
### Description

Just above the `on:` property, add a `name:` property.

I should look like this

```yaml
name: Greetings

on:
```

File path - https://github.com/Pradumnasaraf/Post-My-Message/blob/main/.github/workflows/greetings.ymlthe 

### Screenshots

https://github.com/Pradumnasaraf/Post-My-Message/blob/15be42f5ca1b7ec609bdd6f25c19d6f43645d9b8/.github/workflows/greetings.yml#L1

**Comment by Abhishek-00** [comment]
Hi can you assign this issue to me.

**Comment by Pradumnasaraf** [comment]
> Hi can you assign this issue to me.

Yes, go ahead.
