### ISSUE TITLE
fix the actions/checkout version

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#28]
### Description

The current is **v2** change it to **v3**

```diff
- uses: actions/checkout@v2
+ uses: actions/checkout@v3
```

Link

https://github.com/Pradumnasaraf/Post-My-Message/blob/15be42f5ca1b7ec609bdd6f25c19d6f43645d9b8/.github/workflows/prettier.yml#L9

**Comment by princegcs** [comment]
I am interested

**Comment by yeshwantthota** [comment]
take

**Comment by kalyan-vurugonda** [comment]
Hey @Pradumnasaraf, I would like to contribute to this.

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf, I would like to contribute to this.

Already assigned you one issue on a different repo. Please let other people take part as well

**Comment by gauravrattan** [comment]
@Pradumnasaraf assign me

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf assign me

Go ahaead

**Comment by Pradumnasaraf** [comment]
fixed in #39
