### ISSUE TITLE
fix the actions/checkout version

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#29]
### Description

The current is **v2** change it to **v3**

```diff
- actions/setup-node@v2
+ actions/setup-node@v3
```

Link
https://github.com/Pradumnasaraf/Post-My-Message/blob/15be42f5ca1b7ec609bdd6f25c19d6f43645d9b8/.github/workflows/prettier.yml#L10

**Comment by PratikDey** [comment]
Hi, I would like to contribute to this issue

**Comment by Pradumnasaraf** [comment]
Yes. go ahead
