### ISSUE TITLE
[FEATURE] Change to ES6

### ISSUE THREAD

**Issue by myesua** [Pradumnasaraf/Post-My-Message#42]
### Description

@Pradumnasaraf do you mind turning this code to ES6?

**Comment by Pradumnasaraf** [comment]
Hey,

Thanks for opening the issue
What things will get changed, can you brief me about that brief about that?

**Comment by myesua** [comment]
Yea, basically to meet up with new syntax. Will use type "module" instead of "commonjs"

**Comment by Pradumnasaraf** [comment]
It's done @myesua

**Comment by Pradumnasaraf** [comment]
Fixed in #43
