### ISSUE TITLE
Correct LICENSE name in Readme

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#5]
### Description

Change it to [GPL-3.0 license](https://github.com/Pradumnasaraf/Post-My-Message/blob/main/LICENSE)

### Screenshots

<img width="804" alt="Screenshot 2023-02-10 at 12 32 03 PM" src="https://user-images.githubusercontent.com/51878265/218024724-81ec1419-8996-41c3-8b95-ea4e64abb751.png">

**Comment by kelvinparmar** [comment]
@Pradumnasaraf
If no one working in this issue then assign to me

**Comment by kalyan-vurugonda** [comment]
Hi @Pradumnasaraf, I would like to contribute to this issue

**Comment by Pradumnasaraf** [comment]
Hey, I have already assigned you both one issue each, please refrain from commenting on every issue. @kelvinparmar @kalyan-vurugonda

**Comment by palakbhawsar98** [comment]
Hi @Pradumnasaraf can I work on this issue?

**Comment by Pradumnasaraf** [comment]
Yes, go ahead @palakbhawsar98
