### ISSUE TITLE
Correct the License in package.json

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#6]
### Description

Chnage it to [GPL-3.0 license](https://github.com/Pradumnasaraf/Post-My-Message/blob/main/LICENSE)

https://github.com/Pradumnasaraf/Post-My-Message/blob/53658e31d669e9f41d2e36c8c8a232108b06a778/package.json#L20

**Comment by kelvinparmar** [comment]
@Pradumnasaraf 
Assign to me so I will contribute in this issue

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf Assign to me so I will contribute in this issue

Already assigned you one. This will open for someone else

**Comment by theselaw** [comment]
Hi @Pradumnasaraf  ,Kindly assign this to me.

**Comment by Pradumnasaraf** [comment]
Yes, go ahead

> Hi @Pradumnasaraf ,Kindly assign this to me.

**Comment by theselaw** [comment]
@Pradumnasaraf , kindly check the changes I made.

Thank You.
