### ISSUE TITLE
Improve the description in `package.json`

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Post-My-Message#7]
### Description

Change the description to - **"Send sms or a beautiful quote to your friend by a simple POST request."**

https://github.com/Pradumnasaraf/Post-My-Message/blob/53658e31d669e9f41d2e36c8c8a232108b06a778/package.json#L4

### Screenshots

N/A

**Comment by theselaw** [comment]
Hey, @Pradumnasaraf. I'd like to be assigned to this.

**Comment by Pradumnasaraf** [comment]
> Hey, @Pradumnasaraf. I'd like to be assigned to this.

Already assigned you one issue. This will be open for someone else

**Comment by Shukla007** [comment]
I like to work on this

**Comment by princegcs** [comment]
I am interested in contributing to this issue.

**Comment by Pradumnasaraf** [comment]
Go ahead @Shukla007

Hey, @princegcs, the other person has commented 1st, so assigning it to them. You can have a look at the repo and raise an issue if you find something.

**Comment by princegcs** [comment]
> 

ok.

**Comment by Shukla007** [comment]
> Go ahead @Shukla007
> 
> Hey, @princegcs, the other person has commented 1st, so assigning it to them. You can have a look at the repo and raise an issue if you find something.

thanks @Pradumnasaraf 👍

**Comment by Shukla007** [comment]
@Pradumnasaraf Updated the Package.json file and created a PR
